name: Angular CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci --force
        working-directory: Implementacao/moedas-ui

      - name: Run tests
        run: npm run prettier-check
        working-directory: Implementacao/moedas-ui

      - name: Run tests
        run: npm test -- --watch=false --browsers=ChromeHeadless
        working-directory: Implementacao/moedas-ui

      - name: Build
        run: npm run build
        working-directory: Implementacao/moedas-ui

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        run: npm run deploy -- --no-silent --c=production --base-href /moedas-ui/
        working-directory: Implementacao/moedas-ui
